version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building project..."
      - echo "Hello from AWS CodeBuild!"
artifacts:
  files:
    - '**/*'
