version: 0.2

phases:
  install:
    commands:
      - echo "Installing deps (none for this demo)"
  pre_build:
    commands:
      - echo "Pre-build step on $(date)"
  build:
    commands:
      - echo "Building..."
      - echo "Hello from CodeBuild!"
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  files:
    - '**/*'
  discard-paths: yes
