# This is a basic workflow to help you get started with Actions

name: demo-pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  env:
    Environment: staging
    Name: Demo-Class
    AWS_ACCESS_KEY: ${{ secret.AWS_ACCESS_KEY }}
    AWS_SECRET_KEY: ${{ secret.AWS_SECRET_KEY }}
    AWS_DEFAULT_REGION: us-east-1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: set up env
        run: actions/setup-node@v5
        with: 
          node-version: '>=10.15.0'

      - name: printing the env's
        run: echo $NAME

  terraform:
    - run-on: ubuntu-latest
    steps:

    -name: Checkout code
     uses: actions/setup-node@v5

     name: Install Terraform
     uses: hashicorp/setup-terraform@v3
  with:
    terraform_version: "1.5.7"

    name: Initializing Terraform
    run: terraform init

    name: Plan the Terraform
    run: terraform plan

    name: Applying the Terraform
    run: terraform apply
